-- Generated by scripts/build-platform-seed.mjs.
-- Safe presentation metadata only. Never writes expected_count, expected_count_type, or last_verified.
begin;

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية بريطانية تابعة لمجموعة الجامعات العالمية. تقدم آلاف الدورات المجانية والمدفوعة في مجالات متنوعة مع شهادات إتمام.'),
  description_en = coalesce(description_en, 'A British educational platform from a global university alliance. Offers thousands of free and paid courses across diverse fields with completion certificates.'),
  description_tr = coalesce(description_tr, 'Küresel üniversite grubuna bağlı bir Britanya eğitim platformu. Çeşitli alanlarda binlerce ücretsiz ve ücretli kurs sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=futurelearn.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.futurelearn.com/courses'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 1)
where external_id = 'plat-1';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية تابعة لليونيسف (UNICEF) تقدم دورات مجانية في مجالات حماية الطفل، التعليم، الصحة، التنمية المستدامة، والعمل الإنساني.'),
  description_en = coalesce(description_en, 'A UNICEF educational platform offering free courses in child protection, education, health, sustainable development, and humanitarian work.'),
  description_tr = coalesce(description_tr, 'UNICEF''e bağlı bir eğitim platformu. Çocuk koruma, eğitim, sağlık, sürdürülebilir kalkınma ve insani yardım alanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=unicef.org&sz=128'),
  official_url = coalesce(official_url, 'https://agora.unicef.org/local/catalogue/index.php?filters[]=133'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 2)
where external_id = 'plat-2';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة IBM المجانية لتطوير المهارات التقنية. تغطي الذكاء الاصطناعي، الحوسبة السحابية، الأمن السيبراني، علوم البيانات، وتقنية المعلومات. تقدم شهادات معتمدة.'),
  description_en = coalesce(description_en, 'IBM''s free platform for technical skill development. Covers AI, cloud computing, cybersecurity, data science, and IT. Offers accredited certificates.'),
  description_tr = coalesce(description_tr, 'IBM''nin teknik beceri geliştirme için ücretsiz platformu. Yapay zeka, bulut bilişim, siber güvenlik, veri bilimi ve BT alanlarını kapsar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=skillsbuild.org&sz=128'),
  official_url = coalesce(official_url, 'https://skillsbuild.org/college-students/course-catalog'),
  featured = case when true then true else featured end,
  display_order = coalesce(display_order, 3)
where external_id = 'plat-3';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة فريدة تقدم تجارب عمل افتراضية من شركات عالمية مثل JPMorgan وBCG. تمكنك من اكتساب خبرة عملية حقيقية وبناء سيرتك الذاتية.'),
  description_en = coalesce(description_en, 'A unique platform offering virtual work experience from global companies like JPMorgan and BCG. Gain real practical experience and build your resume.'),
  description_tr = coalesce(description_tr, 'JPMorgan ve BCG gibi küresel şirketlerden sanal iş deneyimleri sunan benzersiz bir platform. Gerçek pratik deneyim kazanın ve özgeçmişinizi oluşturun.'),
  category = coalesce(category, 'business'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=theforage.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.theforage.com/virtual-internships'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 4)
where external_id = 'plat-4';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة مايكروسوفت للتعلم الرسمية. تقدم دورات مجانية ومدفوعة في Azure، Microsoft 365، Power Platform، الأمن السيبراني، والذكاء الاصطناعي مع شهادات معتمدة.'),
  description_en = coalesce(description_en, 'Microsoft''s official learning platform. Offers free and paid courses in Azure, Microsoft 365, Power Platform, cybersecurity, and AI with accredited certificates.'),
  description_tr = coalesce(description_tr, 'Microsoft''un resmi öğrenme platformu. Azure, Microsoft 365, Power Platform, siber güvenlik ve yapay zeka alanlarında ücretsiz ve ücretli kurslar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128'),
  official_url = coalesce(official_url, 'https://learn.microsoft.com/en-us/training/browse/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 5)
where external_id = 'plat-5';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية الاتحاد الدولي للاتصالات (ITU) التابعة للأمم المتحدة. تقدم دورات في الاتصالات، الأمن السيبراني، الذكاء الاصطناعي، والسياسات الرقمية.'),
  description_en = coalesce(description_en, 'The International Telecommunication Union (ITU) Academy, a UN agency. Offers courses in telecommunications, cybersecurity, AI, and digital policies.'),
  description_tr = coalesce(description_tr, 'Birleşmiş Milletler''e bağlı ITU Akademisi. Telekomünikasyon, siber güvenlik, yapay zeka ve dijital politikalar alanlarında kurslar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://academy.itu.int/themes/custom/itu_academy/src/assets/images/logos/ITU-logo.svg'),
  official_url = coalesce(official_url, 'https://academy.itu.int/training-courses/full-catalogue'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 6)
where external_id = 'plat-6';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية رائدة تأسست من Harvard وMIT. تقدم آلاف الدورات من أفضل الجامعات العالمية. يمكنك الاستماع للدورات مجاناً ولكن تحتاج دفع مالي للحصول على الشهادة.'),
  description_en = coalesce(description_en, 'A leading educational platform founded by Harvard and MIT. Offers thousands of courses from top global universities. Audit for free, pay for certificates.'),
  description_tr = coalesce(description_tr, 'Harvard ve MIT tarafından kurulan öncü bir eğitim platformu. En iyi üniversitelerden binlerce kurs sunar. Ücretsiz dinleyin, sertifika için ödeme yapın.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, false),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=edx.org&sz=128'),
  official_url = coalesce(official_url, 'https://www.edx.org/courses'),
  featured = case when true then true else featured end,
  display_order = coalesce(display_order, 7)
where external_id = 'plat-7';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تفاعلية لتعلم البرمجة. تقدم مسارات تعليمية في Python، JavaScript، HTML/CSS، SQL، وغيرها مع بيئة تدريب تفاعلية.'),
  description_en = coalesce(description_en, 'An interactive platform for learning programming. Offers learning paths in Python, JavaScript, HTML/CSS, SQL, and more with an interactive coding environment.'),
  description_tr = coalesce(description_tr, 'Programlama öğrenmek için etkileşimli bir platform. Python, JavaScript, HTML/CSS, SQL ve daha fazlasında öğrenme yolları sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=codecademy.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.codecademy.com/catalog'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 8)
where external_id = 'plat-8';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية تابعة لمعهد الأمم المتحدة للتدريب والبحث (UNITAR). تقدم دورات في التنمية المستدامة، الدبلوماسية، إدارة الأزمات، والقيادة.'),
  description_en = coalesce(description_en, 'An educational platform from the UN Institute for Training and Research (UNITAR). Offers courses in sustainable development, diplomacy, crisis management, and leadership.'),
  description_tr = coalesce(description_tr, 'Birleşmiş Milletler Eğitim ve Araştırma Enstitüsü''ne (UNITAR) bağlı bir eğitim platformu. Sürdürülebilir kalkınma, diplomasi, kriz yönetimi ve liderlik kursları sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ73nI5R5jGuTI2qnICsNl6aBz0o_5Hf5ET5w&s'),
  official_url = coalesce(official_url, 'https://event.unitar.org/full-catalog?search=&type%5B3%5D=3&price%5Bmin%5D=0&price%5Bmax%5D=96591&date%5Bmin%5D=&date%5Bmax%5D=&quick_filter=all'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 9)
where external_id = 'plat-9';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية هواوي الرسمية. تقدم دورات مجانية في الشبكات، الذكاء الاصطناعي، الحوسبة السحابية، الأمن السيبراني، وإنترنت الأشياء مع شهادات معتمدة.'),
  description_en = coalesce(description_en, 'The official Huawei Academy. Offers free courses in networking, AI, cloud computing, cybersecurity, and IoT with accredited certificates.'),
  description_tr = coalesce(description_tr, 'Resmi Huawei Akademisi. Ağ, yapay zeka, bulut bilişim, siber güvenlik ve IoT alanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=huawei.com&sz=128'),
  official_url = coalesce(official_url, 'https://e.huawei.com/en/talent/learning/#/home'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 10)
where external_id = 'plat-10';

update public.platforms
set
  description_ar = coalesce(description_ar, 'تقدم الصفحة مساراً تعليمياً متكاملاً لتعلم اللغة الإنجليزية، مُصمم ليغطي جميع المستويات من المبتدئ حتى المتقدم، مع تركيز خاص على التحضير للدراسة الجامعية. وكذلك لديها دورات في مجالات أخرى مثل التعليم والحضارات.'),
  description_en = coalesce(description_en, 'Offers a complete learning path for English, designed for all levels from beginner to advanced, with a focus on university preparation. Also has courses in other fields like education and civilizations.'),
  description_tr = coalesce(description_tr, 'ingilizce öğrenmek için başlangıçtan ileri seviyeye kadar tüm seviyeleri kapsayan, üniversite hazırlığına odaklanan eksiksiz bir öğrenme yolu sunar. Eğitim ve medeniyetler gibi diğer alanlarda da kursları vardır.'),
  category = coalesce(category, 'languages'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://openlearn.aucegypt.edu/pluginfile.php/1/theme_remui/faviconurl/1767874770/favicon.svg'),
  official_url = coalesce(official_url, 'https://openlearn.aucegypt.edu/course/index.php?categoryid=2'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 11)
where external_id = 'plat-11';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة HP للتعلم مدى الحياة. تقدم دورات مجانية في ريادة الأعمال، التسويق الرقمي، المهارات المالية، وتكنولوجيا المعلومات.'),
  description_en = coalesce(description_en, 'HP''s lifelong learning platform. Offers free courses in entrepreneurship, digital marketing, financial skills, and IT.'),
  description_tr = coalesce(description_tr, 'HP''nin yaşam boyu öğrenme platformu. Girişimcilik, dijital pazarlama, finansal beceriler ve BT alanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'business'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDNOFTTB0IX77-gTg6-9-NHcEriWC8Hc3NYQ&s'),
  official_url = coalesce(official_url, 'https://www.life-global.org/allcourses'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 12)
where external_id = 'plat-12';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة إنفيديا الرائدة في الذكاء الاصطناعي وتعلم الآلة. تقدم دورات مجانية في التعلم العميق، CUDA، معالجة الصور، والذكاء الاصطناعي التوليدي. جميع الدورات مجانية ولكن دورة واحدة فقط بشهادة والباقي بدون شهادات.'),
  description_en = coalesce(description_en, 'Nvidia''s leading platform for AI and machine learning. Offers free courses in deep learning, CUDA, image processing, and generative AI. All courses are free but only one offers a certificate.'),
  description_tr = coalesce(description_tr, 'Yapay zeka ve makine öğreniminde Nvidia''nın öncü platformu. Derin öğrenme, CUDA, görüntü işleme ve üretken yapay zeka alanlarında ücretsiz kurslar sunar. Tüm kurslar ücretsizdir ancak yalnızca biri sertifika verir.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, false),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=nvidia.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.nvidia.com/en-us/training/self-paced-courses/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 13)
where external_id = 'plat-13';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية سيسكو الرسمية. تقدم دورات في الشبكات (CCNA)، الأمن السيبراني، إنترنت الأشياء، وLinux مع شهادات معترف بها عالمياً.'),
  description_en = coalesce(description_en, 'The official Cisco Academy. Offers courses in networking (CCNA), cybersecurity, IoT, and Linux with globally recognized certificates.'),
  description_tr = coalesce(description_tr, 'Resmi Cisco Akademisi. Ağ (CCNA), siber güvenlik, IoT ve Linux alanlarında küresel olarak tanınan sertifikalarla kurslar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://www.cloudcommunications.com/hubfs/Imported_Blog_Media/Cisco-Nov-17-2023-05-40-40-6925-AM.png'),
  official_url = coalesce(official_url, 'https://www.netacad.com/catalogs/learn'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 14)
where external_id = 'plat-14';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة التعلم المفتوح التابعة للجامعة المفتوحة (Open University) في المملكة المتحدة. تقدم مئات الدورات الأكاديمية المجانية بالكامل مع شهادات إتمام.'),
  description_en = coalesce(description_en, 'The Open Learning platform from the Open University in the UK. Offers hundreds of fully free academic courses with completion certificates.'),
  description_tr = coalesce(description_tr, 'BK''deki Açık Üniversite''ye bağlı bir platform. Tamamen ücretsiz yüzlerce akademik kurs ve tamamlama sertifikaları sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=open.edu&sz=128'),
  official_url = coalesce(official_url, 'https://www.open.edu/openlearn/free-courses/full-catalogue'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 15)
where external_id = 'plat-15';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة جوجل الرسمية لبناء المهارات. تقدم دورات مجانية في Google Ads، Analytics، التسويق الرقمي، Android، والسحابة مع شهادات معتمدة.'),
  description_en = coalesce(description_en, 'Google''s official skill-building platform. Offers free courses in Google Ads, Analytics, digital marketing, Android, and cloud with accredited certificates.'),
  description_tr = coalesce(description_tr, 'Google''ın resmi beceri geliştirme platformu. Google Ads, Analytics, dijital pazarlama, Android ve bulut alanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'business'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=google.com&sz=128'),
  official_url = coalesce(official_url, 'https://skillshop.withgoogle.com/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 16)
where external_id = 'plat-16';

update public.platforms
set
  description_ar = coalesce(description_ar, 'تطبيق ومنصة تفاعلية لتعلم البرمجة بلغة مبسطة. تدعم العديد من لغات البرمجة مثل Python، Java، C++، JavaScript وتتيح التعلم عبر الجوال.'),
  description_en = coalesce(description_en, 'An interactive app and platform for learning programming in a simplified way. Supports many languages like Python, Java, C++, JavaScript with mobile learning.'),
  description_tr = coalesce(description_tr, 'Basitleştirilmiş bir şekilde programlama öğrenmek için etkileşimli bir uygulama ve platform. Mobil öğrenme ile Python, Java, C++, JavaScript gibi birçok dili destekler.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, false),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=sololearn.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.sololearn.com/en/learn'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 17)
where external_id = 'plat-17';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية ELSEVIER للتدريب على البحث العلمي. تقدم دورات مجانية في الكتابة الأكاديمية، النشر العلمي، تحليل البيانات البحثية، وإدارة المراجع.'),
  description_en = coalesce(description_en, 'Elsevier''s research training academy. Offers free courses in academic writing, scientific publishing, research data analysis, and reference management.'),
  description_tr = coalesce(description_tr, 'Elsevier''in araştırma eğitim akademisi. Akademik yazım, bilimsel yayıncılık, araştırma veri analizi ve referans yönetimi alanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=elsevier.com&sz=128'),
  official_url = coalesce(official_url, 'https://researcheracademy.elsevier.com/learn'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 18)
where external_id = 'plat-18';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أشهر منصة مجانية لتعلم برمجة الويب. تقدم دروساً تفاعلية في HTML، CSS، JavaScript، Python، SQL، PHP وأكثر.'),
  description_en = coalesce(description_en, 'The most popular free platform for learning web programming. Offers interactive tutorials in HTML, CSS, JavaScript, Python, SQL, PHP and more.'),
  description_tr = coalesce(description_tr, 'Web programlama öğrenmek için en popüler ücretsiz platform. HTML, CSS, JavaScript, Python, SQL, PHP ve daha fazlasında etkileşimli dersler sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, false),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=w3schools.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.w3schools.com/where_to_start.asp'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 19)
where external_id = 'plat-19';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية غير ربحية تقدم تعليماً مجانياً للجميع. تغطي الرياضيات، العلوم، البرمجة، التاريخ، والاقتصاد بمحتوى عالي الجودة.'),
  description_en = coalesce(description_en, 'A non-profit educational platform offering free education for everyone. Covers math, science, programming, history, and economics with high-quality content.'),
  description_tr = coalesce(description_tr, 'Herkes için ücretsiz eğitim sunan kar amacı gütmeyen bir eğitim platformu. Yüksek kaliteli içerikle matematik, fen, programlama, tarih ve ekonomi konularını kapsar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=khanacademy.org&sz=128'),
  official_url = coalesce(official_url, 'https://www.khanacademy.org/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 20)
where external_id = 'plat-20';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكبر منصة للدورات التعليمية عالمياً. تضم آلاف الدورات في جميع المجالات. بعض الدورات مجانية وأخرى مدفوعة بأسعار متفاوتة. يمكنك الحصول على دورات Udemy مجاناً عبر موقع DiscUdemy.'),
  description_en = coalesce(description_en, 'The world''s largest marketplace for learning courses. Hosts thousands of courses in all fields. Some are free, others paid. Get Udemy courses free via DiscUdemy.'),
  description_tr = coalesce(description_tr, 'Dünyanın en büyük öğrenme kurs pazarı. Tüm alanlarda binlerce kurs barındırır. Bazıları ücretsiz, diğerleri ücretlidir. DiscUdemy üzerinden Udemy kurslarını ücretsiz alın.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=discudemy.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.discudemy.com/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 21)
where external_id = 'plat-21';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة علم البيانات والذكاء الاصطناعي التابعة لجوجل. تقدم دورات مجانية، مسابقات، ومشاريع عملية في Python، التعلم الآلي، وتحليل البيانات.'),
  description_en = coalesce(description_en, 'Google''s data science and AI platform. Offers free courses, competitions, and hands-on projects in Python, machine learning, and data analysis.'),
  description_tr = coalesce(description_tr, 'Google''ın veri bilimi ve yapay zeka platformu. Python, makine öğrenimi ve veri analizinde ücretsiz kurslar, yarışmalar ve uygulamalı projeler sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=kaggle.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.kaggle.com/learn'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 22)
where external_id = 'plat-22';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة جيت هاب التعليمية. تقدم دورات تفاعلية مجانية في Git، GitHub، DevOps، وأتمتة workflows.'),
  description_en = coalesce(description_en, 'GitHub''s learning platform. Offers free interactive courses in Git, GitHub, DevOps, and workflow automation.'),
  description_tr = coalesce(description_tr, 'GitHub''ın öğrenme platformu. Git, GitHub, DevOps ve iş akışı otomasyonu alanlarında ücretsiz etkileşimli kurslar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=github.com&sz=128'),
  official_url = coalesce(official_url, 'https://skills.github.com/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 23)
where external_id = 'plat-23';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة جوجل كلاود التعليمية. تقدم دورات مجانية في الحوسبة السحابية، البيانات الضخمة، التعلم الآلي، وبنية الخدمات السحابية مع شهادات.'),
  description_en = coalesce(description_en, 'Google Cloud''s learning platform. Offers free courses in cloud computing, big data, machine learning, and cloud architecture with certificates.'),
  description_tr = coalesce(description_tr, 'Google Cloud öğrenme platformu. Bulut bilişim, büyük veri, makine öğrenimi ve bulut mimarisi alanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Multilingual']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=cloud.google.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.skills.google/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 24)
where external_id = 'plat-24';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة غير ربحية لتعلم البرمجة مجاناً بالكامل. تقدم مسارات تعليمية في تطوير الويب، Python، التعلم الآلي، وعلوم البيانات مع شهادات مجانية.'),
  description_en = coalesce(description_en, 'A non-profit platform for learning programming completely free. Offers learning paths in web development, Python, machine learning, and data science with free certificates.'),
  description_tr = coalesce(description_tr, 'Tamamen ücretsiz programlama öğrenmek için kar amacı gütmeyen bir platform. Web geliştirme, Python, makine öğrenimi ve veri biliminde ücretsiz sertifikalarla öğrenme yolları sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=freecodecamp.org&sz=128'),
  official_url = coalesce(official_url, 'https://www.freecodecamp.org/learn'),
  featured = case when true then true else featured end,
  display_order = coalesce(display_order, 25)
where external_id = 'plat-25';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية رائدة تقدم دورات من أفضل الجامعات والشركات. المحتوى مجاني بالكامل، ولكن تحتاج للدفع للحصول على الشهادة.'),
  description_en = coalesce(description_en, 'A leading educational platform from top universities and companies. Content is completely free to access, but you need to pay for the certificate.'),
  description_tr = coalesce(description_tr, 'En iyi üniversitelerden ve şirketlerden kurslar sunan öncü bir platform. İçerik tamamen ücretsizdir ancak sertifika için ödeme yapmanız gerekir.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, false),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=coursera.org&sz=128'),
  official_url = coalesce(official_url, 'https://www.coursera.org/courses'),
  featured = case when true then true else featured end,
  display_order = coalesce(display_order, 26)
where external_id = 'plat-26';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية تقدم دورات في إدارة المشاريع، الأمن السيبراني، الذكاء الاصطناعي، وتحليل البيانات مع شهادات مهنية.'),
  description_en = coalesce(description_en, 'An educational platform offering courses in project management, cybersecurity, AI, and data analysis with professional certificates.'),
  description_tr = coalesce(description_tr, 'Proje yönetimi, siber güvenlik, yapay zeka ve veri analizi alanlarında profesyonel sertifikalarla kurslar sunan bir eğitim platformu.'),
  category = coalesce(category, 'business'),
  has_free_content = coalesce(has_free_content, false),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=simplilearn.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.simplilearn.com/skillup-free-online-courses'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 27)
where external_id = 'plat-27';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليم مجاني رائدة تقدم آلاف الدورات في مختلف المجالات مع شهادات مجانية. تغطي المهارات الوظيفية والتقنية والشخصية.'),
  description_en = coalesce(description_en, 'A leading free education platform offering thousands of courses across various fields with free certificates. Covers job, technical, and personal skills.'),
  description_tr = coalesce(description_tr, 'Binlerce kursta ücretsiz sertifikalar sunan öncü bir ücretsiz eğitim platformu. İş, teknik ve kişisel becerileri kapsar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=alison.com&sz=128'),
  official_url = coalesce(official_url, 'https://alison.com/courses'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 28)
where external_id = 'plat-28';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية سايلور غير الربحية. تقدم دورات أكاديمية مجانية بالكامل تعادل المقررات الجامعية مع شهادات إتمام.'),
  description_en = coalesce(description_en, 'The non-profit Saylor Academy. Offers fully free academic courses equivalent to university-level courses with completion certificates.'),
  description_tr = coalesce(description_tr, 'Kar amacı gütmeyen Saylor Akademisi. Üniversite düzeyinde tamamen ücretsiz akademik kurslar ve tamamlama sertifikaları sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=saylor.org&sz=128'),
  official_url = coalesce(official_url, 'https://learn.saylor.org/course/index.php'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 29)
where external_id = 'plat-29';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة سعودية لتعلم البرمجة والتقنيات الحديثة باللغة العربية. تقدم دورات مجانية في لغات البرمجة والأمن السيبراني وقواعد البيانات.'),
  description_en = coalesce(description_en, 'A Saudi platform for learning programming and modern technologies in Arabic. Offers free courses in programming languages, cybersecurity, and databases.'),
  description_tr = coalesce(description_tr, 'Arapça programlama ve modern teknolojiler öğrenmek için bir Suudi platformu. Programlama dilleri, siber güvenlik ve veritabanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=satr.codes&sz=128'),
  official_url = coalesce(official_url, 'https://satr.codes'),
  featured = case when true then true else featured end,
  display_order = coalesce(display_order, 30)
where external_id = 'plat-30';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة تعليمية عربية من مؤسسة الملكة رانيا للتعليم والتنمية. تقدم مساقات مجانية عبر الإنترنت باللغة العربية من أفضل الجامعات والخبراء العرب والعالميين مع شهادات إتمام.'),
  description_en = coalesce(description_en, 'An Arab educational platform from the Queen Rania Foundation. Offers free online courses in Arabic from top Arab and global universities and experts.'),
  description_tr = coalesce(description_tr, 'Kraliçe Rania Vakfı''ndan bir Arap eğitim platformu. En iyi Arap ve küresel üniversitelerden Arapça ücretsiz çevrimiçi kurslar sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=edraak.org&sz=128'),
  official_url = coalesce(official_url, 'https://www.edraak.org/explore/?type=course'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 31)
where external_id = 'plat-31';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة عربية تضم آلاف الدورات المجانية في مختلف المجالات. تقدم دورات في البرمجة، اللغات، التصميم، الإدارة، والتسويق مع شهادات معتمدة.'),
  description_en = coalesce(description_en, 'An Arab platform with thousands of free courses across various fields. Offers courses in programming, languages, design, management, and marketing with accredited certificates.'),
  description_tr = coalesce(description_tr, 'Binlerce ücretsiz kursu olan bir Arap platformu. Programlama, diller, tasarım, yönetim ve pazarlama alanlarında akredite sertifikalarla kurslar sunar.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=m3aarf.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.m3aarf.com/certified/courses'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 32)
where external_id = 'plat-32';

update public.platforms
set
  description_ar = coalesce(description_ar, 'المنصة العربية للتعليم المفتوح. تقدم مواد أكاديمية مجانية باللغة العربية في شتى المجالات والتخصصات من محاضرين متطوعين. تمنح شهادات إتمام لبعض المواد.'),
  description_en = coalesce(description_en, 'The Arab open education platform. Offers free academic materials in Arabic across various fields from volunteer instructors. Grants completion certificates for some courses.'),
  description_tr = coalesce(description_tr, 'Arap açık eğitim platformu. Gönüllü eğitmenlerden çeşitli alanlarda Arapça ücretsiz akademik materyaller sunar. Bazı dersler için tamamlama sertifikası verir.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic']::text[]),
  logo_url = coalesce(logo_url, 'https://rwaq-production.s3.amazonaws.com/uploads/rwaq_image_params/platform-logo-sidebar.png'),
  official_url = coalesce(official_url, 'https://www.rwaq.org/courses'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 33)
where external_id = 'plat-33';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة متخصصة في تعلم علوم البيانات والذكاء الاصطناعي والتحليل الإحصائي. تقدم مئات الدورات التفاعلية والتمارين العملية بلغة Python وR وSQL وغيرها.'),
  description_en = coalesce(description_en, 'A specialized platform for learning data science, AI, and statistical analysis. Offers hundreds of interactive courses and hands-on exercises in Python, R, SQL, and more.'),
  description_tr = coalesce(description_tr, 'Veri bilimi, yapay zeka ve istatistiksel analiz öğrenmek için özel bir platform. Python, R, SQL ve daha fazlasında yüzlerce etkileşimli kurs sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, false),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=datacamp.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.datacamp.com/courses'),
  featured = case when true then true else featured end,
  display_order = coalesce(display_order, 34)
where external_id = 'plat-34';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية Semrush لتعلم التسويق الرقمي. تقدم دورات مجانية في تحسين محركات البحث (SEO)، التسويق بالمحتوى، الإعلانات المدفوعة (PPC)، ووسائل التواصل الاجتماعي مع شهادات معتمدة.'),
  description_en = coalesce(description_en, 'Semrush Academy for digital marketing learning. Offers free courses in SEO, content marketing, PPC, and social media with accredited certificates.'),
  description_tr = coalesce(description_tr, 'Dijital pazarlama öğrenimi için Semrush Akademisi. SEO, içerik pazarlaması, PPC ve sosyal medya alanlarında ücretsiz kurslar sunar.'),
  category = coalesce(category, 'business'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=semrush.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.semrush.com/academy/'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 35)
where external_id = 'plat-35';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة التعليم التركية الرسمية من هيئة تقنية المعلومات والاتصالات. تقدم دورات مجانية في البرمجة، الأمن السيبراني، علم البيانات، الذكاء الاصطناعي، وتقنية المعلومات مع شهادات معتمدة.'),
  description_en = coalesce(description_en, 'Turkey''s official education platform from the ICT Authority. Offers free courses in programming, cybersecurity, data science, AI, and IT with accredited certificates.'),
  description_tr = coalesce(description_tr, 'BTK''nın resmi eğitim platformu. Programlama, siber güvenlik, veri bilimi, yapay zeka ve BT alanlarında ücretsiz kurslar ve sertifikalar sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Turkish']::text[]),
  logo_url = coalesce(logo_url, 'https://assets-btkakademi-gov-tr.akamaized.net/api/service/v1/public/51/assets/logo.png?ts=1738148275127'),
  official_url = coalesce(official_url, 'https://www.btkakademi.gov.tr/portal/courses'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 36)
where external_id = 'plat-36';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية MATLAB من MathWorks. تقدم دورات تفاعلية في MATLAB وSimulink ومعالجة الإشارات والصور والتعلم الآلي. بعض الدورات مجانية والأخرى مدفوعة.'),
  description_en = coalesce(description_en, 'MATLAB Academy by MathWorks. Offers interactive courses in MATLAB, Simulink, signal processing, image processing, and machine learning. Some courses are free, others paid.'),
  description_tr = coalesce(description_tr, 'MathWorks''tan MATLAB Akademisi. MATLAB, Simulink, sinyal işleme, görüntü işleme ve makine öğreniminde etkileşimli kurslar sunar. Bazı kurslar ücretsiz, bazıları ücretlidir.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=mathworks.com&sz=128'),
  official_url = coalesce(official_url, 'https://matlabacademy.mathworks.com/?page=1&fq=course&sort=featured'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 37)
where external_id = 'plat-37';

update public.platforms
set
  description_ar = coalesce(description_ar, 'أكاديمية HubSpot لتعلم التسويق والمبيعات وخدمة العملاء. تقدم دورات مجانية بالكامل مع شهادات معتمدة في التسويق الداخلي والتجارة الإلكترونية.'),
  description_en = coalesce(description_en, 'HubSpot Academy for learning marketing, sales, and customer service. Offers completely free courses with accredited certificates in inbound marketing and e-commerce.'),
  description_tr = coalesce(description_tr, 'Pazarlama, satış ve müşteri hizmetleri için HubSpot Akademisi. Gelen pazarlama ve e-ticaret alanlarında tamamen ücretsiz kurslar sunar.'),
  category = coalesce(category, 'business'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic','English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=hubspot.com&sz=128'),
  official_url = coalesce(official_url, 'https://academy.hubspot.com/courses?contentType=COURSE'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 38)
where external_id = 'plat-38';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة عالمية للتحديات البرمجية واختبار المهارات. تقدم دورات تفاعلية ومشاريع عملية في Python، Java، SQL، والخوارزميات مع شهادات إتقان.'),
  description_en = coalesce(description_en, 'A global platform for coding challenges and skill testing. Offers interactive courses and hands-on projects in Python, Java, SQL, and algorithms with skill certificates.'),
  description_tr = coalesce(description_tr, 'Kodlama zorlukları ve beceri testi için küresel bir platform. Python, Java, SQL ve algoritmalarda etkileşimli kurslar ve beceri sertifikaları sunar.'),
  category = coalesce(category, 'technology'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['English']::text[]),
  logo_url = coalesce(logo_url, 'https://www.google.com/s2/favicons?domain=hackerrank.com&sz=128'),
  official_url = coalesce(official_url, 'https://www.hackerrank.com/skills-verification'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 39)
where external_id = 'plat-39';

update public.platforms
set
  description_ar = coalesce(description_ar, 'منصة عربية تقدم آلاف الدورات المجانية في مختلف المجالات مثل البرمجة والتصميم والتسويق والإدارة مع شهادات إتمام.'),
  description_en = coalesce(description_en, 'An Arab platform offering thousands of free courses in various fields like programming, design, marketing, and management with completion certificates.'),
  description_tr = coalesce(description_tr, 'Programlama, tasarım, pazarlama ve yönetim gibi çeşitli alanlarda binlerce ücretsiz kurs sunan bir Arap platformu.'),
  category = coalesce(category, 'academic'),
  has_free_content = coalesce(has_free_content, true),
  certificate_available = coalesce(certificate_available, true),
  languages = coalesce(languages, array['Arabic']::text[]),
  logo_url = coalesce(logo_url, 'https://www.coursat.org/images/logo.png'),
  official_url = coalesce(official_url, 'https://www.coursat.org/categories'),
  featured = case when false then true else featured end,
  display_order = coalesce(display_order, 40)
where external_id = 'plat-40';

commit;
