let allPlatforms=[];let activeTab='all';let platformDataSource='fallback';let deferredInstallPrompt=null;
const $=id=>document.getElementById(id);
const STORAGE={favorites:'dunya-favorites-v2',compare:'dunya-platform-compare-v3',compareLegacy:'dunya-compare-v2',views:'dunya-views-v2',recent:'dunya-recent-v2',theme:'dunya-theme-v2'};
const FEATURED_IDS=['plat-26','plat-25','plat-3','plat-7','plat-34','plat-30'];
const els={search:$('searchInput'),heroSearch:$('heroSearchInput'),grid:$('platformGrid'),featured:$('featuredGrid'),categoryGrid:$('categoryGrid'),filterLang:$('filterLang'),filterCategory:$('filterCategory'),filterPricing:$('filterPricing'),filterVerification:$('filterVerification'),filterFree:$('filterFree'),filterCert:$('filterCert'),sort:$('sortSelect'),status:$('platformDataStatus'),compareDock:$('compareDock')};
function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch(_){return f}}function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}}
function getFavorites(){return new Set(readJSON(STORAGE.favorites,[]))}function setFavorites(s){writeJSON(STORAGE.favorites,[...s])}function getCompare(){return new Set(readJSON(STORAGE.compare,[]))}function setCompare(s){writeJSON(STORAGE.compare,[...s])}function getViews(){return readJSON(STORAGE.views,{})}function getRecent(){return readJSON(STORAGE.recent,[]).map((x,i)=>typeof x==='string'?{id:x,ts:Date.now()-i}:x).filter(x=>x&&x.id)}
function migrateComparisonStorage(){let current=null,hasCurrent=false;try{const raw=localStorage.getItem(STORAGE.compare);hasCurrent=raw!==null;if(hasCurrent)current=JSON.parse(raw)}catch(_){}const legacy=readJSON(STORAGE.compareLegacy,[]);const ids=PlatformDirectory.migrateComparisonIds(hasCurrent&&Array.isArray(current)?current:null,legacy,allPlatforms.map(p=>p.id),3);setCompare(new Set(ids))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function validUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)}catch(_){return false}}
function platformById(id){return allPlatforms.find(p=>p.id===id)}function detailUrl(p){return `platform.html?id=${encodeURIComponent(p.id)}&lang=${encodeURIComponent(currentLang)}`}
function descriptionFor(p){return pf(p,'description')||p.description_en||p.description_ar||''}function languagesLabel(p){return(p.languages||[]).map(translateLang).join(' · ')||getText('unknown')}
function populateSelect(el,values,labelFn){if(!el)return;const old=el.value;el.innerHTML=`<option value="">${esc(getText('all'))}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(labelFn?labelFn(v):v)}</option>`).join('');if(values.includes(old))el.value=old}
function hydrateFilterOptions(){const o=PlatformDirectory.getFilterOptions(allPlatforms);populateSelect(els.filterLang,o.languages,translateLang);populateSelect(els.filterCategory,o.categories,translateCat);populateSelect(els.filterPricing,o.pricingModels,translatePricing);populateSelect(els.filterVerification,['recent','outdated','unverified'],translateVerification)}
function renderStats(){const s=PlatformDirectory.getStats(allPlatforms);$('statPlatforms').textContent=s.platforms;$('statFree').textContent=s.free;$('statCert').textContent=s.certificates;$('statLang').textContent=s.languages;$('allBadge').textContent=allPlatforms.length;$('favBadge').textContent=getFavorites().size;$('recentBadge').textContent=getRecent().length}
function currentState(){return{query:els.search.value,category:els.filterCategory.value,language:els.filterLang.value,pricingModel:els.filterPricing.value,verification:els.filterVerification.value,freeOnly:els.filterFree.checked,certificateOnly:els.filterCert.checked,sort:['viewed','recent'].includes(els.sort.value)?'recommended':els.sort.value}}
function visiblePlatforms(){const fav=getFavorites(),recent=getRecent(),recentMap=Object.fromEntries(recent.map(x=>[x.id,x.ts]));let list=PlatformDirectory.getVisiblePlatforms(allPlatforms,currentState());if(activeTab==='favorites')list=list.filter(p=>fav.has(p.id));if(activeTab==='recent')list=list.filter(p=>recentMap[p.id]);if(els.sort.value==='viewed'){const views=getViews();list.sort((a,b)=>(views[b.id]||0)-(views[a.id]||0)||a.name.localeCompare(b.name))}if(els.sort.value==='recent')list.sort((a,b)=>(recentMap[b.id]||0)-(recentMap[a.id]||0));return list}
function logoHtml(p,name){return p.logoUrl?`<img class="platform-logo" src="${esc(p.logoUrl)}" alt="${esc(name)}" loading="lazy" onerror="this.onerror=null;this.src='icon.svg'">`:`<img class="platform-logo" src="icon.svg" alt="${esc(name)}">`}
function platformCard(p,compact=false){const name=p.name||'',facts=PlatformDirectory.cardFacts(p,currentLang),fav=getFavorites().has(p.id),selected=getCompare().has(p.id),official=validUrl(p.officialUrl);return `<article class="platform-card${compact?' compact':''}" data-id="${esc(p.id)}"><div class="platform-card-head"><a href="${detailUrl(p)}" class="logo-shell">${logoHtml(p,name)}</a><div class="card-icon-actions"><button class="round-action ${fav?'active':''}" data-action="favorite" data-id="${esc(p.id)}" type="button" aria-pressed="${fav}">${fav?'♥':'♡'}</button><button class="round-action" data-action="share" data-id="${esc(p.id)}" type="button">↗</button></div></div><div class="platform-card-body"><div class="badge-row"><span class="tag">${esc(translateCat(p.category))}</span><span class="verification-badge ${facts.verification}">${esc(translateVerification(facts.verification))}</span></div><a class="title-link" href="${detailUrl(p)}"><h3>${esc(name)}</h3></a>${compact?'':`<p class="platform-desc">${esc(descriptionFor(p))}</p>`}<div class="fact-grid"><div><span>${esc(getText('language'))}</span><strong>${esc(languagesLabel(p))}</strong></div><div><span>${esc(getText('price'))}</span><strong>${esc(translatePricing(p.pricingModel))}</strong></div><div><span>${esc(getText('freeContent'))}</span><strong>${p.hasFreeContent?getText('yes'):getText('no')}</strong></div><div><span>${esc(getText('certificate'))}</span><strong>${p.certificateAvailable?getText('yes'):getText('no')}</strong></div></div><div class="official-count"><span>${esc(getText('officialContent'))}</span><strong>${esc(facts.countLabel)}</strong></div><div class="card-actions"><button class="btn-inline ${selected?'active':''}" data-action="compare" data-id="${esc(p.id)}" type="button" aria-pressed="${selected}">⚖ ${esc(selected?getText('selected'):getText('compare'))}</button><a class="btn-inline" href="${detailUrl(p)}">${esc(getText('details'))}</a>${official?`<a class="btn-inline official" href="${esc(p.officialUrl)}" target="_blank" rel="noopener noreferrer">${esc(getText('officialSite'))} ↗</a>`:''}</div></div></article>`}
function renderDirectory(){const list=visiblePlatforms();$('resultsCount').textContent=list.length;els.grid.innerHTML=list.length?list.map(p=>platformCard(p)).join(''):`<div class="no-results">⌕ <strong>${esc(getText('noResults'))}</strong></div>`}
function renderFeatured(){const list=PlatformDirectory.getFeatured(allPlatforms,FEATURED_IDS).slice(0,6);els.featured.innerHTML=list.map(p=>platformCard(p,true)).join('')}
function renderCategories(){const icons=['⌘','◈','◎','✦','▦','↗'];els.categoryGrid.innerHTML=PlatformDirectory.getCategoryGroups(allPlatforms).slice(0,8).map((g,i)=>`<button class="category-card" type="button" data-category="${esc(g.category)}"><span>${icons[i%icons.length]}</span><strong>${esc(translateCat(g.category))}</strong><small>${g.count}</small></button>`).join('')}
function renderDataStatus(){els.status.className='data-status '+platformDataSource;els.status.textContent=(platformDataSource==='supabase'?'✓ ':'⚠ ')+getText(platformDataSource==='supabase'?'dataSupabase':'dataFallback')}
function updateCompareDock(){const items=[...getCompare()].map(platformById).filter(Boolean);$('compareCount').textContent=`${items.length}/3`;$('compareNames').textContent=items.map(p=>p.name).join(' · ');els.compareDock.classList.toggle('show',items.length>0)}
function rerender(){renderStats();renderFeatured();renderCategories();renderDirectory();updateCompareDock()}
function toggleFavorite(id){const s=getFavorites();s.has(id)?s.delete(id):s.add(id);setFavorites(s);renderStats();renderFeatured();renderDirectory()}
function toggleCompare(id){const result=PlatformCore.toggleComparison([...getCompare()],id,3);if(result.blocked){showToast(getText('maxCompare'));return}setCompare(new Set(result.ids));updateCompareDock();renderFeatured();renderDirectory()}
async function sharePlatform(id){const p=platformById(id);if(!p)return;const url=new URL(detailUrl(p),location.href).href;try{if(navigator.share)await navigator.share({title:p.name,text:descriptionFor(p),url});else{await navigator.clipboard.writeText(url);showToast(getText('copied'))}}catch(_){}}
function showToast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function openModal(id){const m=$(id);if(!m)return;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');const f=m.querySelector('button,a,input,select');if(f)f.focus()}function closeModal(id){const m=$(id);if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');if(!document.querySelector('.modal.open'))document.body.classList.remove('modal-open')}
function buildCompareTable(){const items=[...getCompare()].map(platformById).filter(Boolean),rows=PlatformDirectory.comparisonRows(items,currentLang);if(!rows.length){$('compareTable').innerHTML='';return}const row=(label,fn)=>`<tr><th>${esc(label)}</th>${rows.map(r=>`<td>${fn(r)}</td>`).join('')}</tr>`;$('compareTable').innerHTML=`<table class="compare-table"><thead><tr><th>${esc(getText('compareTitle'))}</th>${rows.map(r=>`<th>${esc(r.name)}</th>`).join('')}</tr></thead><tbody>${row(getText('category'),r=>esc(translateCat(r.category)))}${row(getText('price'),r=>esc(translatePricing(r.pricingModel)))}${row(getText('freeContent'),r=>esc(r.hasFreeContent?getText('yes'):getText('no')))}${row(getText('certificate'),r=>esc(r.certificateAvailable?getText('yes'):getText('no')))}${row(getText('language'),r=>esc(r.languages.map(translateLang).join(' · ')||getText('unknown')))}${row(getText('officialContent'),r=>esc(r.countLabel))}${row(getText('verification'),r=>esc(translateVerification(r.verification)))}${row(getText('lastVerified'),r=>esc(r.lastVerified||getText('unknown')))}${row(getText('bestFor'),r=>esc(r.bestFor||getText('unknown')))}${row('',r=>validUrl(r.officialUrl)?`<a href="${esc(r.officialUrl)}" target="_blank" rel="noopener noreferrer">${esc(getText('officialSite'))} ↗</a>`:'—')}</tbody></table>`}
function resetFilters(){els.search.value='';els.heroSearch.value='';els.filterLang.value='';els.filterCategory.value='';els.filterPricing.value='';els.filterVerification.value='';els.filterFree.checked=false;els.filterCert.checked=false;els.sort.value='recommended';activeTab='all';document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab==='all'));renderDirectory()}
function pickOption(values,kind){const terms=kind==='english'?['english','انجليزي','إنجليزي']:kind==='arabic'?['arabic','عربي','العربيه','العربية']:kind==='technology'?['technology','تكنولوجيا','برمجه','برمجة']:['business','اعمال','أعمال','تسويق'];return values.find(v=>terms.some(t=>PlatformCore.normalizeText(v).includes(PlatformCore.normalizeText(t))))||''}
function applyQuickFilter(kind){const o=PlatformDirectory.getFilterOptions(allPlatforms);activeTab='all';if(kind==='free')els.filterFree.checked=true;else if(kind==='certificate')els.filterCert.checked=true;else if(kind==='english'||kind==='arabic')els.filterLang.value=pickOption(o.languages,kind);else els.filterCategory.value=pickOption(o.categories,kind);renderDirectory();document.querySelector('#explore').scrollIntoView({behavior:'smooth'})}
function buildQuiz(){const o=PlatformDirectory.getFilterOptions(allPlatforms);$('quizForm').innerHTML=`<div class="quiz-grid"><label>${getText('qCategory')}<select id="quizCategory"><option value="">${getText('anyCategory')}</option>${o.categories.map(v=>`<option value="${esc(v)}">${esc(translateCat(v))}</option>`).join('')}</select></label><label>${getText('qLanguage')}<select id="quizLanguage"><option value="">${getText('anyLanguage')}</option>${o.languages.map(v=>`<option value="${esc(v)}">${esc(translateLang(v))}</option>`).join('')}</select></label><label>${getText('qBudget')}<select id="quizFree"><option value="yes">${getText('freePreferred')}</option><option value="any">${getText('paidOkay')}</option></select></label><label>${getText('qCertificate')}<select id="quizCert"><option value="yes">${getText('certImportant')}</option><option value="any">${getText('certNotImportant')}</option></select></label></div><button class="btn btn-primary" id="runQuiz" type="button">${getText('showResults')}</button>`;$('quizResults').innerHTML='';$('runQuiz').onclick=runQuiz}
function runQuiz(){const cat=$('quizCategory').value,lang=$('quizLanguage').value,wantFree=$('quizFree').value==='yes',wantCert=$('quizCert').value==='yes';const ranked=allPlatforms.map(p=>{let points=10,max=10;if(cat){max+=40;if(p.category===cat)points+=40}if(lang){max+=25;if((p.languages||[]).includes(lang))points+=25}if(wantFree){max+=15;if(p.hasFreeContent)points+=15}if(wantCert){max+=10;if(p.certificateAvailable)points+=10}return{p,pct:Math.round(points/max*100)}}).sort((a,b)=>b.pct-a.pct).slice(0,3);$('quizResults').innerHTML=`<div class="quiz-results"><h3>${getText('quizResults')}</h3>${ranked.map((r,i)=>`<a class="match-card" href="${detailUrl(r.p)}"><span>${i+1}</span><strong>${esc(r.p.name)}</strong><b>${r.pct}% ${getText('match')}</b></a>`).join('')}</div>`}
const PATHS={programming:[['Free Code Camp','W3 School','Solo Learn'],['HackerRank','GitHub Learn','Kaggle'],['Coursera','Edx','Udemy']],ai:[['Kaggle','DataCamp','Free Code Camp'],['IBM Skills Build','Nvidia','Google Cloud'],['Kaggle','MATLAB Academy','Coursera']],cyber:[['Cisco','Huawei','IBM Skills Build'],['Microsoft','Google Cloud','ITU Academy'],['Cisco','Huawei','Coursera']],business:[['HP Life','Coursera','Alison'],['HubSpot Academy','Semrush','Google (Skillshop)'],['Forage','Udemy','Coursera']],english:[['openlearn.aucegypt.edu','Open Learn','Khan Academy'],['Coursera','Edx','FutureLearn'],['Open Learn','Coursera','FutureLearn']]};
function findByName(n){const q=PlatformCore.normalizeText(n);return allPlatforms.find(p=>PlatformCore.normalizeText(p.name)===q)||allPlatforms.find(p=>PlatformCore.normalizeText(p.name).includes(q)||q.includes(PlatformCore.normalizeText(p.name)))}
function buildPath(){const labels={programming:'goalProgramming',ai:'goalAI',cyber:'goalCyber',business:'goalBusiness',english:'goalEnglish'};$('pathBuilder').innerHTML=`<div class="path-controls"><label>${getText('pathGoal')}<select id="pathGoal">${Object.keys(PATHS).map(k=>`<option value="${k}">${getText(labels[k])}</option>`).join('')}</select></label><button class="btn btn-primary" id="generatePath" type="button">${getText('generatePath')}</button></div>`;$('pathResults').innerHTML='';$('generatePath').onclick=()=>{const stages=PATHS[$('pathGoal').value];$('pathResults').innerHTML=`<div class="learning-path">${stages.map((names,i)=>`<div class="path-stage"><span>${i+1}</span><div><small>${getText('stage')} ${i+1}</small><div class="stage-platforms">${names.map(findByName).filter(Boolean).map(p=>`<a href="${detailUrl(p)}">${esc(p.name)}</a>`).join('')}</div></div></div>`).join('')}</div>`}}
function setTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem(STORAGE.theme,theme)}catch(_){};$('themeToggle').textContent=theme==='dark'?'☀':'◐'}function initTheme(){let s;try{s=localStorage.getItem(STORAGE.theme)}catch(_){};setTheme(s||(window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'))}
function changeLang(lang){setLang(lang);applyTranslations();hydrateFilterOptions();rerender();renderDataStatus();document.title=getText('siteName')}
function bindEvents(){[els.filterLang,els.filterCategory,els.filterPricing,els.filterVerification,els.filterFree,els.filterCert,els.sort].forEach(el=>el&&el.addEventListener('change',renderDirectory));els.search.addEventListener('input',()=>{els.heroSearch.value=els.search.value;renderDirectory()});els.heroSearch.addEventListener('input',()=>{els.search.value=els.heroSearch.value;renderDirectory()});$('resetFilters').onclick=resetFilters;$('langSwitcher').onchange=e=>changeLang(e.target.value);$('themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');document.querySelectorAll('.tab-btn').forEach(btn=>btn.onclick=()=>{activeTab=btn.dataset.tab;document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b===btn));renderDirectory()});$('quickFilterChips').onclick=e=>{const b=e.target.closest('[data-quick-filter]');if(b)applyQuickFilter(b.dataset.quickFilter)};els.categoryGrid.onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;activeTab='all';els.filterCategory.value=b.dataset.category;renderDirectory();document.querySelector('#explore').scrollIntoView({behavior:'smooth'})};document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){e.preventDefault();const id=a.dataset.id;if(a.dataset.action==='favorite')toggleFavorite(id);if(a.dataset.action==='compare')toggleCompare(id);if(a.dataset.action==='share')sharePlatform(id)}const c=e.target.closest('[data-close]');if(c)closeModal(c.dataset.close);if(e.target.classList.contains('modal'))closeModal(e.target.id)});$('heroQuizBtn').onclick=()=>{buildQuiz();openModal('quizModal')};$('heroCompareBtn').onclick=$('navCompare').onclick=$('compareNow').onclick=()=>{buildCompareTable();openModal('compareModal')};$('clearCompare').onclick=()=>{setCompare(new Set());rerender()};$('randomBtn').onclick=()=>{const list=visiblePlatforms().length?visiblePlatforms():allPlatforms;if(list.length)location.href=detailUrl(list[Math.floor(Math.random()*list.length)])};$('pathBtn').onclick=()=>{buildPath();openModal('pathModal')};document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();els.heroSearch.focus()}if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))})}
function registerPWA(){if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installBtn').hidden=true}else showToast(getText('installed'))}}
async function init(){const params=new URLSearchParams(location.search);setLang(params.get('lang')||currentLang);initTheme();applyTranslations();$('langSwitcher').value=currentLang;try{const loaded=await PlatformData.loadPlatforms({...SUPABASE_CONFIG,staticPlatforms:Array.isArray(PLATFORMS_DATA)?PLATFORMS_DATA:[]});allPlatforms=loaded.platforms;platformDataSource=loaded.source;migrateComparisonStorage();hydrateFilterOptions();renderDataStatus();rerender();bindEvents();registerPWA();document.title=getText('siteName')}catch(err){console.error(err);els.grid.innerHTML=`<div class="no-results">${esc(getText('errorLoading'))}</div>`}}
document.addEventListener('DOMContentLoaded',init);
